version: 2.1
jobs:
  build-api:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    working_directory: ~/tmp

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          name: Install lumino-explorer-api and run tests
          command: |
                      cd lumino-explorer-api
                      sudo env "PATH=$PATH" mvn install
                      sudo env "PATH=$PATH" mvn verify       
#  build-web:
#    working_directory: ~/tpm
#    docker:
#      - image: circleci/node:10
#    steps:
#      - checkout      
#      - run:
#          name: Install lumino-explorer-web and run tests
#          command: |
#                    cd lumino-explorer-web
#                    npm install
#                    npm run-script build
#                    npm test
workflows:
    commit:
        jobs:
            - build-api
 #           - build-web


