version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    
    working_directory: ~/tmp
    
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout
      - run:
          name: Build & Test Explorer API
          command: |
                    sudo apt-get install -y maven
                    cd lumino-explorer-api
                    sudo mvn install
                    sudo mvn verify
      
#      - run:
#          name: Prepare npm
#          command: |
#                    curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
#                    sudo apt update
#                    sudo apt-get install -y nodejs
#                    sudo apt install npm
#                    sudo apt install build-essential
#      
#      - run:
#          name: Build & Test Explorer Web
#          command: |
#                    cd lumino-explorer-web
#                    npm install
#                    npm test

