version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:latest
    working_directory: ~/tmp

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          name: Install lumino-explorer-api and run tests
          command: |
                      cd lumino-explorer-api
                      sudo env "PATH=$PATH" mvn install
                      sudo env "PATH=$PATH" mvn verify
      - run:
          name: Prepare npm
          command: |
                    curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
                    sudo apt update
                    sudo apt-get install -y nodejs
                    sudo apt install npm
                    sudo apt install build-essential
      
      - run:
          name: Build & Test Explorer Web
          command: |
                    cd ~/tmp/lumino-explorer-web
                    npm install
                    npm build
                    npm test          

workflows:
    commit:
        jobs:
            - build


