version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7
    
    working_directory: ~/tmp

    steps:
      - checkout
      - run:
          name: Build & Test Explorer Web
          command: |
                    ls
                    cd /home/circleci/tmp/lumino-explorer/lumino-explorer-web
                    npm install
                    npm test
      - run:
          name: Build & Test Explorer API
          command: |
                    cd /home/circleci/tmp/lumino-explorer/lumino-explorer-web
                    mvn install
                    mvn test
